export const GET_RECIPES = "GET_RECIPES";
export const DELETE_RECIPE = "GET_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";