version: "3"

volumes:
  static:
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static:/static
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             gunicorn -w 4 app.wsgi -b 0.0.0.0:8000"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=app"
      - "DB_USER=postgres"
      - "DB_PASS=supersecretpassword"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - "POSTGRES_DB=app"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=supersecretpassword"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - 80:80