# Generated by Django 2.2.11 on 2020-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='A dish best served cold', max_length=255),
        ),
    ]
