# Generated by Django 2.2.11 on 2020-03-17 18:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200317_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='http://127.0.0.1:8000/media/uploads/recipe/5e2a3dfb-2daf-41ab-94b4-899b2c8d8403.jpg', upload_to=core.models.recipe_image_file_path),
        ),
    ]
