# Generated by Django 2.2.8 on 2019-12-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Ingredient'),
            preserve_default=False,
        ),
    ]
