# Generated by Django 2.2.8 on 2019-12-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191212_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'get_latest_by': 'creation_date'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
