# Generated by Django 2.2.8 on 2019-12-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191219_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
