# Generated by Django 2.2.8 on 2019-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191219_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='cup', max_length=30),
        ),
    ]
