# Generated by Django 2.2.8 on 2020-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191231_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='methods',
            field=models.TextField(default='Step 1: x'),
        ),
    ]
